name: Javier Rivera is a Designer
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

author: Javier Rivera
author_email: javier@javirivera.com

url: http://javirivera.com

baseurl: ''

permalink: pretty

gems: [jekyll-paginate, jekyll-paginate-category]

paginate: 5

sass:
    sass_dir: /assets/_sass
